spring:
  server:
    max-http-request-size: 25MB
  application:
    name: @project.name@
  output:
    ansi.enabled: always
  data:
    mongodb:
      auto-index-creation: true
  logging:
    level:
      root: INFO
      org.springframework.web.reactive.function.client: WARN

springdoc:
  swagger-ui.path: /docs

app:
  version: @project.version@
  name: @project.name@
  tmp-assets-dir: "./assets_tmp"
  assets-dir: "./assets"

keycloak:
  admin:
    baseUrl: http://localhost:8085
    realm: "vehicle"
    client-id: "someId"
    client-secret: "key"
    regular-user-role-id: "roleId"
    regular-user-role-name: "REGULAR_USER"
    frontend-client-id: "profiler-fe"