spring:
  server:
    max-http-request-size: 15MB
  application:
    name: @project.name@
  output:
    ansi.enabled: always
  data:
    mongodb:
      auto-index-creation: true
  logging:
    level:
      root: INFO
      org.springframework.web.reactive.function.client: WARN

springdoc:
  swagger-ui.path: /docs

app:
  version: @project.version@
  name: @project.name@
  tmp-assets-dir: "./assets_tmp"
  assets-dir: "./assets"